In [2]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import csv
from pandas.tseries.offsets import MonthEnd
from datetime import datetime, timedelta, date
import requests
import json 
import ta

In [7]:
#data with feature engineering
fields = ['Date', 'Open','High','Low','Close','Volume','RSI','MACD','Ichimoku_Span_A','Ichimoku_Span_B','ATR',
         'BB_High_Indicator','BB_Low_Indicator']
MSFT_df = pd.read_csv(r"/Users/fahad/project_repo/data/interim/MSFT.csv", usecols=fields)

In [8]:
#daily data with indicators and OHLC, drop the OHLC for this dataset
MSFT_df.head()
MSFT_df = MSFT_df.drop(['Open','High','Low','Close','Volume'], axis=1)

In [9]:
#/Users/fahad/project_repo/data/final/Tech/MSFT

In [10]:
MSFT_df.head()

,Date,RSI,MACD,Ichimoku_Span_A,Ichimoku_Span_B,ATR,BB_High_Indicator,BB_Low_Indicator
0,2019-07-10,0.517256,0.325001,0.231939,0.236938,0.125655,0.0,0.0
1,2019-07-09,0.000000,0.324198,0.231939,0.236938,0.127104,0.0,0.0
2,2019-07-08,0.350682,0.324890,0.231939,0.236938,0.128062,0.0,0.0
3,2019-07-05,0.400295,0.325302,0.231939,0.236938,0.128110,0.0,0.0
4,2019-07-03,0.559390,0.326239,0.231939,0.236938,0.126996,0.0,0.0

In [13]:
#monthly data split into various training and test intervals
MSFT_98_train = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/1998_MSFT_train.csv", index_col=1)

MSFT_98_test = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/1998_MSFT_test.csv", index_col=1)

MSFT_02_train = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/2002_MSFT_train.csv", index_col=1)

MSFT_02_test = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/2002_MSFT_test.csv", index_col=1)

MSFT_06_train = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/2006_MSFT_train.csv", index_col=1)

MSFT_06_test = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/2006_MSFT_test.csv", index_col=1)

MSFT_10_train = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/2010_MSFT_train.csv", index_col=1)

MSFT_10_test = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/2010_MSFT_test.csv", index_col=1)

MSFT_14_train = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/2014_MSFT_train.csv", index_col=1)

MSFT_14_test = pd.read_csv("/Users/fahad/project_repo/data/final/MSFT/2014_MSFT_test.csv", index_col=1)

In [14]:
#ADD LABELS TO THE TRAINING AND TEST DATAFRAMES AND RETURN DICTIONARIES WITH DATE:LABEL FORMAT
MSFT_98_train_labels = labelling(MSFT_98_train)

MSFT_98_test_labels  = labelling(MSFT_98_test)

MSFT_02_train_labels = labelling(MSFT_02_train)

MSFT_02_test_labels  = labelling(MSFT_02_test)

MSFT_06_train_labels = labelling(MSFT_06_train)

MSFT_06_test_labels  = labelling(MSFT_06_test)

MSFT_10_train_labels = labelling(MSFT_10_train)

MSFT_10_test_labels  = labelling(MSFT_10_test)

MSFT_14_train_labels = labelling(MSFT_14_train)

MSFT_14_test_labels  = labelling(MSFT_14_test)

In [15]:
#GET 30 DAY PERIODS FOR EACH MONTH AND CREATE DICTIONARY FOR 30DAYS PRIOR TO EACH DATE 
MSFT_98_train_flattened= get_ndays_monthly_flattened(MSFT_98_train,MSFT_df,30)

MSFT_98_test_flattened= get_ndays_monthly_flattened(MSFT_98_test,MSFT_df,30)

MSFT_02_train_flattened = get_ndays_monthly_flattened(MSFT_02_train,MSFT_df,30)

MSFT_02_test_flattened = get_ndays_monthly_flattened(MSFT_02_test,MSFT_df,30)

MSFT_06_train_flattened = get_ndays_monthly_flattened(MSFT_06_train,MSFT_df,30)

MSFT_06_test_flattened = get_ndays_monthly_flattened(MSFT_06_test,MSFT_df,30)

MSFT_10_train_flattened = get_ndays_monthly_flattened(MSFT_10_train,MSFT_df,30)

MSFT_10_test_flattened = get_ndays_monthly_flattened(MSFT_10_test,MSFT_df,30)

MSFT_14_train_flattened = get_ndays_monthly_flattened(MSFT_14_train,MSFT_df,30)

MSFT_14_test_flattened = get_ndays_monthly_flattened(MSFT_14_test,MSFT_df,30)

In [16]:
#assign labels to a dataframe object
MSFT_98_train_labels_df = pd.Series(MSFT_98_train_labels).to_frame("Label")

MSFT_98_test_labels_df  =  pd.Series(MSFT_98_test_labels).to_frame("Label")

MSFT_02_train_labels_df =  pd.Series(MSFT_02_train_labels).to_frame("Label")

MSFT_02_test_labels_df =  pd.Series(MSFT_02_test_labels).to_frame("Label")

MSFT_06_train_labels_df =  pd.Series(MSFT_06_train_labels).to_frame("Label")

MSFT_06_test_labels_df =  pd.Series(MSFT_06_test_labels).to_frame("Label")

MSFT_10_train_labels_df =  pd.Series(MSFT_10_train_labels).to_frame("Label")

MSFT_10_test_labels_df =  pd.Series(MSFT_10_test_labels).to_frame("Label")

MSFT_14_train_labels_df =  pd.Series(MSFT_14_train_labels).to_frame("Label")

MSFT_14_test_labels_df =  pd.Series(MSFT_14_test_labels).to_frame("Label")

In [17]:
#CREATE DATAFRAME FROM FLATTENED DICTIONARY OF ARRAYS FOR TRAINING AND TEST DATA
MSFT_98_train_flat_df = pd.DataFrame.from_dict(MSFT_98_train_flattened).T

MSFT_98_test_flat_df = pd.DataFrame.from_dict(MSFT_98_test_flattened).T

MSFT_02_train_flat_df = pd.DataFrame.from_dict(MSFT_02_train_flattened).T

MSFT_02_test_flat_df = pd.DataFrame.from_dict(MSFT_02_test_flattened).T

MSFT_06_train_flat_df = pd.DataFrame.from_dict(MSFT_06_train_flattened).T

MSFT_06_test_flat_df = pd.DataFrame.from_dict(MSFT_06_test_flattened).T

MSFT_10_train_flat_df = pd.DataFrame.from_dict(MSFT_10_train_flattened).T

MSFT_10_test_flat_df = pd.DataFrame.from_dict(MSFT_10_test_flattened).T

MSFT_14_train_flat_df = pd.DataFrame.from_dict(MSFT_14_train_flattened).T

MSFT_14_test_flat_df = pd.DataFrame.from_dict(MSFT_14_test_flattened).T

In [18]:

#JOIN THE LABEL DATAFRAME AND THE FLATTENED DATAFRAME ON THE INDEX WHICH IS THE DATE
MSFT_98_train_flat_df = MSFT_98_train_flat_df.merge(MSFT_98_train_labels_df, left_index=True, right_index=True)

MSFT_98_test_flat_df  = MSFT_98_test_flat_df.merge(MSFT_98_test_labels_df, left_index=True, right_index=True)

MSFT_02_train_flat_df = MSFT_02_train_flat_df.merge(MSFT_02_train_labels_df, left_index=True, right_index=True)

MSFT_02_test_flat_df = MSFT_02_test_flat_df.merge(MSFT_02_test_labels_df, left_index=True, right_index=True)

MSFT_06_train_flat_df = MSFT_06_train_flat_df.merge(MSFT_06_train_labels_df, left_index=True, right_index=True)

MSFT_06_test_flat_df =MSFT_06_test_flat_df.merge(MSFT_06_test_labels_df, left_index=True, right_index=True)

MSFT_10_train_flat_df =MSFT_10_train_flat_df.merge(MSFT_10_train_labels_df, left_index=True, right_index=True)

MSFT_10_test_flat_df =MSFT_10_test_flat_df.merge(MSFT_10_test_labels_df, left_index=True, right_index=True)

MSFT_14_train_flat_df =MSFT_14_train_flat_df.merge(MSFT_14_train_labels_df, left_index=True, right_index=True)

MSFT_14_test_flat_df =MSFT_14_test_flat_df.merge(MSFT_14_test_labels_df, left_index=True, right_index=True)

In [19]:
MSFT_98_train_flat_df.head()

,0,1,2,3,4,5,6,7,8,9,...,201,202,203,204,205,206,207,208,209,Label
1998-03-31,0.627285,0.373432,0.500535,0.519246,0.231693,0.0,0.0,0.593716,0.375060,0.500535,...,0.0,0.0,0.226505,0.019309,0.457683,0.712130,0.453455,0.0,0.0,1
1998-04-30,0.403578,0.305363,0.475177,0.588950,0.276414,0.0,0.0,0.398206,0.299860,0.475177,...,1.0,0.0,0.954846,0.966738,0.509452,0.514381,0.640977,0.0,0.0,1
1998-05-29,0.691593,0.397587,0.531022,0.598253,0.255372,0.0,0.0,0.641265,0.393773,0.517112,...,0.0,1.0,0.233407,0.259587,0.494930,0.558306,0.266415,0.0,0.0,0
1998-06-30,0.440966,0.357870,0.644377,0.636887,0.290104,0.0,0.0,0.426021,0.369316,0.644173,...,0.0,0.0,0.510333,0.361165,0.499703,0.595590,0.298256,0.0,0.0,1
1998-07-31,0.358593,0.250476,0.596634,0.595164,0.371578,0.0,0.0,0.273269,0.242065,0.600234,...,0.0,0.0,0.486961,0.394788,0.617644,0.629785,0.248232,0.0,0.0,1

In [21]:

#export dataframes which are now ready to be used by the model 
MSFT_list_of_names = ['MSFT_98_train_flat_df_Tech', 'MSFT_98_test_flat_df_Tech', 'MSFT_02_train_flat_df_Tech', 'MSFT_02_test_flat_df_Tech'
                     ,'MSFT_06_train_flat_df_Tech','MSFT_06_test_flat_df_Tech','MSFT_10_train_flat_df_Tech','MSFT_10_test_flat_df_Tech',
                     'MSFT_14_train_flat_df_Tech','MSFT_14_test_flat_df_Tech']

MSFT_list = [MSFT_98_train_flat_df, MSFT_98_test_flat_df, MSFT_02_train_flat_df, MSFT_02_test_flat_df,
            MSFT_06_train_flat_df, MSFT_06_test_flat_df, MSFT_10_train_flat_df, MSFT_10_test_flat_df,
            MSFT_14_train_flat_df, MSFT_14_test_flat_df]

for i in range(len(MSFT_list)):
    
    str_name = MSFT_list_of_names[i]
    
    export_MSFT = MSFT_list[i].to_csv("/Users/fahad/project_repo/data/final/Tech/MSFT/{}.csv".format(str_name))

In [11]:
def labelling(dataframe):
    """This generates labels for the dataframes we wish to predict price.
    A label of 1 suggests an increase in price between months while a label of 0 indicates
    a decrease in price. If the current price is greater than the previous price then a"""
    empty_dict = dict()
    prev_close =0
    counter = 0
    for index,cols in dataframe.iterrows():
        counter +=1
        current_close = cols['Close']
        if float(prev_close) <= float(current_close):
            #signals an increase in price between last month and next month
            empty_dict[index] = 1
        elif float(prev_close) >= float(current_close):
            empty_dict[index]=0

        #reassign prev close to the current close     
        prev_close = current_close
    
    return empty_dict

In [12]:
def get_ndays_monthly_flattened(dataframe_period_end,dataframe_subperiod,n):
    """returns a dictionary which contains key value pair of the month-end date as key and
    value is the proceeding n days. Returns it as a dictionary of dataframes.
    dataframe period end refers to the dataframe which will act as the period end i.e monthly end date
    sub_period dataframe refers to the dataframe with the preceeding n days, i.e daily"""
    empty_dict = dict()
    count = 0
    for end in dataframe_period_end.index:
#         print ("month end/:%s" % end)
        
        month_key = dataframe_period_end.index[count+1]
        
#         print ("month key:%s" % month_key)
        
        last_index = dataframe_period_end.index[-1]
        
#         print ("last index:%s " % last_index)
        
        if (month_key != last_index):
            temp_df = dataframe_subperiod.loc[dataframe_subperiod['Date']<end].head(n)
#             print ("\n")
#             print (temp_df.head(5))
            temp_df = temp_df.drop(['Date'], axis=1)
            
            empty_dict[month_key]= temp_df.values.flatten()
            count +=1
        else:
            pass
       
    return empty_dict