In [2]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import csv
from pandas.tseries.offsets import MonthEnd
from datetime import datetime, timedelta, date
import requests
import json 
import ta

In [3]:
#assign dates to dataframe index
PFE_df = pd.read_csv("/Users/fahad/project_repo/data/final/PFE/PFE_normalised.csv", index_col=0)
dates = PFE_df.index
PFE_df['Date'] =dates

In [4]:
PFE_df

,Open,High,Low,Close,Volume,RSI,MACD,Ichimoku_Span_A,Ichimoku_Span_B,ATR,BB_High_Indicator,BB_Low_Indicator,Date
2019-08-15,0.600374,0.598889,0.614872,0.601098,0.017380,0.462995,0.465808,0.493114,0.498150,0.226222,0.0,0.0,2019-08-15
2019-08-14,0.617228,0.615156,0.621200,0.604713,0.115180,1.000000,0.466739,0.493114,0.498150,0.230835,0.0,0.0,2019-08-14
2019-08-13,0.630580,0.637540,0.647336,0.630423,0.138415,1.000000,0.478840,0.493114,0.498150,0.259598,0.0,0.0,2019-08-13
2019-08-12,0.654103,0.651294,0.637156,0.635512,0.131081,1.000000,0.483546,0.493114,0.498150,0.285250,0.0,0.0,2019-08-12
2019-08-09,0.666399,0.665049,0.673746,0.661221,0.071574,1.000000,0.501538,0.493114,0.498150,0.305547,0.0,0.0,2019-08-09
2019-08-08,0.664528,0.668285,0.687227,0.675147,0.064825,1.000000,0.516609,0.493114,0.498150,0.294809,0.0,0.0,2019-08-08
2019-08-07,0.663192,0.663835,0.666868,0.667381,0.093543,0.857976,0.511898,0.493114,0.498150,0.299278,0.0,0.0,2019-08-07
2019-08-06,0.677626,0.677994,0.683752,0.677290,0.093439,0.881119,0.514213,0.493114,0.498150,0.297310,0.0,0.0,2019-08-06
2019-08-05,0.692852,0.692017,0.682000,0.677558,0.140009,0.881720,0.511129,0.493114,0.498150,0.316041,0.0,0.0,2019-08-05
2019-08-02,0.705961,0.711165,0.718801,0.705410,0.084048,0.926384,0.533888,0.493114,0.498150,0.339071,0.0,0.0,2019-08-02
2019-08-01,0.707565,0.713323,0.716939,0.712105,0.158561,0.933363,0.548096,0.493114,0.498150,0.337913,0.0,0.0,2019-08-01
2019-07-31,0.715317,0.741640,0.739773,0.727906,0.174094,0.947036,0.567083,0.493114,0.498150,0.353744,0.0,0.0,2019-07-31
2019-07-30,0.748196,0.757012,0.742249,0.726567,0.304842,0.926953,0.568587,0.493114,0.498150,0.376194,0.0,0.0,2019-07-30
2019-07-29,0.810746,0.831446,0.817629,0.797804,0.201450,0.966908,0.645511,0.493114,0.498150,0.487560,0.0,0.0,2019-07-29
2019-07-26,0.823844,0.836030,0.847586,0.841725,0.057217,0.976178,0.731715,0.493114,0.498150,0.503269,0.0,0.0,2019-07-26
2019-07-25,0.828388,0.831446,0.850367,0.830477,0.045454,0.895894,0.751085,0.493114,0.498150,0.476998,0.0,0.0,2019-07-25
2019-07-24,0.832932,0.831446,0.845966,0.836369,0.047454,0.900492,0.750156,0.493114,0.498150,0.455070,0.0,0.0,2019-07-24
2019-07-23,0.828923,0.837648,0.856420,0.841725,0.052325,0.904898,0.735950,0.493114,0.498150,0.429424,0.0,0.0,2019-07-23
2019-07-22,0.828388,0.831985,0.850917,0.834494,0.028998,0.841742,0.697461,0.493114,0.498150,0.407723,0.0,0.0,2019-07-22
2019-07-19,0.838011,0.837109,0.856970,0.833155,0.065475,0.829289,0.653497,0.493114,0.498150,0.384051,0.0,0.0,2019-07-19
2019-07-18,0.829190,0.833064,0.850917,0.840921,0.032900,0.843529,0.620567,0.493114,0.498150,0.364534,0.0,0.0,2019-07-18
2019-07-17,0.835338,0.836570,0.855869,0.832351,0.041564,0.755440,0.573483,0.493114,0.498150,0.344651,0.0,0.0,2019-07-17
2019-07-16,0.827319,0.830636,0.848992,0.835297,0.052214,0.764411,0.535942,0.493114,0.498150,0.327245,0.0,0.0,2019-07-16
2019-07-15,0.813419,0.825243,0.842411,0.832619,0.054902,0.733346,0.498267,0.493114,0.643193,0.315280,0.0,0.0,2019-07-15
2019-07-12,0.830527,0.831176,0.836062,0.823246,0.098729,0.628262,0.452824,0.493114,0.652489,0.317230,0.0,0.0,2019-07-12
2019-07-11,0.841486,0.846548,0.846241,0.838779,0.114653,0.702341,0.440958,0.493114,0.665280,0.326086,0.0,0.0,2019-07-11
2019-07-10,0.850307,0.861381,0.875402,0.867702,0.038106,0.791579,0.470493,0.628954,0.673139,0.332548,0.0,0.0,2019-07-10
2019-07-09,0.844280,0.853020,0.871551,0.849223,0.034540,0.634905,0.454681,0.637852,0.680999,0.325516,0.0,0.0,2019-07-09
2019-07-08,0.854317,0.854908,0.862747,0.847349,0.066811,0.620197,0.435953,0.650096,0.682848,0.323565,0.0,0.0,2019-07-08
2019-07-05,0.867950,0.867853,0.884756,0.863953,0.048042,0.686641,0.444159,0.657619,0.682848,0.327389,0.0,0.0,2019-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999-09-27,0.625769,0.629180,0.641503,0.626754,0.005076,0.280677,0.052577,0.697610,0.669641,0.689934,0.0,0.0,1999-09-27
1999-09-24,0.630794,0.630879,0.631187,0.618372,0.013648,0.261086,0.073365,0.707745,0.669641,0.665828,0.0,0.0,1999-09-24
1999-09-23,0.669206,0.666262,0.656964,0.641805,0.010562,0.372827,0.146351,0.708674,0.669641,0.683068,0.0,0.0,1999-09-23
1999-09-22,0.659182,0.674703,0.670720,0.675281,0.014317,0.497968,0.265499,0.710053,0.670596,0.679283,0.0,0.0,1999-09-22
1999-09-21,0.647501,0.659520,0.663842,0.653535,0.009316,0.423554,0.316829,0.710053,0.701418,0.660340,0.0,0.0,1999-09-21
1999-09-20,0.659182,0.659520,0.674159,0.666926,0.000450,0.472329,0.381178,0.710053,0.703344,0.622920,0.0,0.0,1999-09-20
1999-09-17,0.664207,0.661219,0.679331,0.663578,0.008956,0.459312,0.422934,0.731251,0.728342,0.581587,0.0,0.0,1999-09-17
1999-09-16,0.645817,0.657829,0.663842,0.658543,0.006466,0.438136,0.445661,0.760754,0.737063,0.558609,0.0,0.0,1999-09-16
1999-09-15,0.664207,0.674703,0.670720,0.651848,0.010660,0.408725,0.452579,0.762598,0.739945,0.550505,0.0,0.0,1999-09-15
1999-09-14,0.675889,0.676375,0.675892,0.663578,0.006810,0.470225,0.479606,0.762598,0.739945,0.545163,0.0,0.0,1999-09-14
1999-09-13,0.674231,0.679746,0.691353,0.685324,0.009374,0.566644,0.534288,0.762598,0.739945,0.529179,0.0,0.0,1999-09-13
1999-09-10,0.714298,0.711785,0.703403,0.685324,0.013229,0.566644,0.567460,0.759832,0.739945,0.529763,0.0,0.0,1999-09-10
1999-09-09,0.714328,0.715156,0.717159,0.710445,0.003952,0.661416,0.626559,0.759375,0.739945,0.532525,0.0,0.0,1999-09-09
1999-09-08,0.700962,0.718528,0.724036,0.720487,0.005031,0.692443,0.673607,0.759375,0.739945,0.515259,0.0,0.0,1999-09-08
1999-09-07,0.732692,0.733684,0.746375,0.728843,0.004247,0.717311,0.707383,0.761218,0.739945,0.497008,0.0,0.0,1999-09-07
1999-09-03,0.710986,0.735383,0.736059,0.738886,0.011078,0.745815,0.733298,0.763520,0.742842,0.488901,0.0,0.0,1999-09-03
1999-09-02,0.687597,0.696602,0.703403,0.705410,0.004674,0.516723,0.680633,0.764906,0.742842,0.516561,0.0,0.0,1999-09-02
1999-09-01,0.704304,0.713457,0.713720,0.722148,0.006589,0.583818,0.663700,0.759366,0.742842,0.507022,0.0,0.0,1999-09-01
1999-08-31,0.726009,0.738754,0.715425,0.698715,0.019650,0.463313,0.603429,0.748776,0.742842,0.529019,0.0,0.0,1999-08-31
1999-08-30,0.705961,0.745496,0.730914,0.728843,0.012587,0.577996,0.607069,0.748776,0.742842,0.553848,0.0,0.0,1999-08-30
1999-08-27,0.741059,0.753910,0.737792,0.722148,0.012748,0.544128,0.589597,0.750155,0.749576,0.563660,0.0,0.0,1999-08-27
1999-08-26,0.756081,0.769094,0.765303,0.747268,0.023671,0.627824,0.611933,0.752456,0.754400,0.586014,0.0,0.0,1999-08-26
1999-08-25,0.729350,0.762352,0.756692,0.769014,0.034518,0.685499,0.652158,0.743236,0.754400,0.580355,1.0,0.0,1999-08-25
1999-08-24,0.712644,0.732012,0.732620,0.733878,0.028449,0.515254,0.607365,0.733095,0.754400,0.603701,0.0,0.0,1999-08-24
1999-08-23,0.684256,0.726942,0.708548,0.722148,0.039858,0.468419,0.549864,0.729429,0.754400,0.612171,0.0,0.0,1999-08-23
1999-08-20,0.639134,0.676375,0.655259,0.676968,0.023347,0.326831,0.432124,0.725719,0.754400,0.670650,0.0,0.0,1999-08-20
1999-08-19,0.609054,0.625809,0.629453,0.631762,0.004169,0.234007,0.282831,0.718343,0.754400,0.698570,0.0,1.0,1999-08-19
1999-08-18,0.632451,0.634250,0.634625,0.618372,0.006912,0.211416,0.174412,0.718343,0.754400,0.673847,0.0,1.0,1999-08-18
1999-08-17,0.627453,0.632551,0.629453,0.640145,0.011377,0.306801,0.155881,0.713270,0.754400,0.655293,0.0,0.0,1999-08-17
1999-08-16,0.597380,0.622438,0.619137,0.621719,0.007890,0.266575,0.129153,0.710968,0.754400,0.649088,0.0,0.0,1999-08-16

In [7]:
PFE_2003 = pd.read_csv("/Users/fahad/project_repo/data/final/PFE/2003_PFE.csv", index_col=0)
PFE_2015 = pd.read_csv("/Users/fahad/project_repo/data/final/PFE/2015_PFE.csv", index_col=0)

In [8]:
PFE_2015

               Open     High      Low  Close      Volume        Date
2015-01-30  31.2700  33.5000  31.0100  31.25   598304700  2015-01-30
2015-02-27  31.4400  34.9700  31.0200  34.32   605350100  2015-02-27
2015-03-31  34.3200  35.4500  33.6300  34.79   654758000  2015-03-31
2015-04-30  34.8400  35.5300  33.7100  33.93   556389300  2015-04-30
2015-05-29  33.8600  34.9900  33.2100  34.75   437881000  2015-05-29
2015-06-30  34.7700  34.9200  33.3300  33.53   507655700  2015-06-30
2015-07-31  33.5600  36.4600  33.0800  36.06   497482000  2015-07-31
2015-08-31  36.2900  36.3000  28.4700  32.22   545900700  2015-08-31
2015-09-30  31.4600  33.9600  30.6400  31.41   580612600  2015-09-30
2015-10-30  31.3000  36.0700  31.1000  33.82   679709800  2015-10-30
2015-11-30  34.1700  35.2500  30.9889  32.77   849907000  2015-11-30
2015-12-31  33.0000  33.8300  31.8400  32.28   740264900  2015-12-31
2016-01-29  31.8500  32.2400  29.5900  30.49   703021900  2016-01-29
2016-02-29  30.3400  30.9023  28.2500  29.67   850735400  2016-02-29
2016-03-31  29.7900  30.6100  28.7421  29.64  1044553500  2016-03-31
2016-04-29  29.4400  33.5000  29.4100  32.71  1186276100  2016-04-29
2016-05-31  32.5600  34.7500  32.4962  34.70   611622900  2016-05-31
2016-06-30  34.7000  35.5000  33.5300  35.21   575249100  2016-06-30
2016-07-29  35.1500  37.1900  35.1200  36.89   350803300  2016-07-29
2016-08-31  37.0200  37.3900  34.6100  34.80   479724100  2016-08-31
2016-09-30  34.7300  34.9900  33.3000  33.87   398195300  2016-09-30
2016-10-31  33.7300  34.0000  31.6100  31.71   397091500  2016-10-31
2016-11-30  30.9400  33.8300  29.8300  32.14   740937300  2016-11-30
2016-12-30  32.2500  33.3000  30.5100  32.48   507600300  2016-12-30
2017-01-31  32.7000  33.7000  30.9000  31.73   526191300  2017-01-31
2017-02-28  31.5100  34.4600  31.2600  34.12   519070400  2017-02-28
2017-03-31  34.2700  34.7500  33.7200  34.21   515406000  2017-03-31
2017-04-28  34.1100  34.5200  33.4700  33.92   353037500  2017-04-28
2017-05-31  33.8900  33.9900  31.9700  32.65   531420900  2017-05-31
2017-06-30  32.6700  34.4800  31.6700  33.59   465512800  2017-06-30
2017-07-31  33.4800  33.9700  32.6900  33.16   305432700  2017-07-31
2017-08-31  33.0400  34.0200  32.3200  33.92   388679900  2017-08-31
2017-09-29  33.9400  36.2100  33.7500  35.70   387075500  2017-09-29
2017-10-31  35.6700  36.7800  34.1000  35.06   345560700  2017-10-31
2017-11-30  35.0100  36.4800  34.8000  36.26   284986400  2017-11-30
2017-12-29  36.2900  37.3500  35.1500  36.22   314792100  2017-12-29
2018-01-31  36.3800  39.4300  36.2300  37.04   479581700  2018-01-31
2018-02-28  36.6097  37.4000  33.2000  36.31   557684600  2018-02-28
2018-03-29  36.1200  37.0400  34.3236  35.49   481192500  2018-03-29
2018-04-30  35.4200  37.2700  34.7600  36.61   424062600  2018-04-30
2018-05-31  35.5800  36.2500  34.3688  35.93   485553500  2018-05-31
2018-06-29  36.2600  36.8000  35.7300  36.28   433961300  2018-06-29
2018-07-31  36.0000  39.9900  36.0000  39.93   396825300  2018-07-31
2018-08-31  39.6300  42.7700  39.4900  41.52   474885000  2018-08-31
2018-09-28  41.4800  44.4600  41.2200  44.07   350653500  2018-09-28
2018-10-31  44.0300  45.8091  41.6600  43.06   573682900  2018-10-31
2018-11-30  43.2000  46.2591  42.3500  46.23   481866000  2018-11-30
2018-12-31  46.3700  46.4700  40.4200  43.65   536815600  2018-12-31
2019-01-31  43.1200  43.7000  39.4700  42.45   599578800  2019-01-31
2019-02-28  42.8700  43.7800  41.2100  43.35   427804700  2019-02-28
2019-03-29  43.6100  43.7900  40.3400  42.47   525812100  2019-03-29
2019-04-30  42.5800  43.2800  38.4200  40.61   461322900  2019-04-30
2019-05-31  40.5900  42.4800  39.8700  41.52   524538400  2019-05-31
2019-06-28  41.6334  44.2900  41.5700  43.32   437559700  2019-06-28

In [12]:
#ADD LABELS TO THE TRAINING AND TEST DATAFRAMES AND RETURN DICTIONARIES WITH DATE:LABEL FORMAT
PFE_2003_labels = labelling(PFE_2003)
PFE_2015_labels = labelling(PFE_2015)

In [13]:
PFE_2003_flattened= get_ndays_monthly_flattened(PFE_2003,PFE_df,30)
PFE_2015_flattened= get_ndays_monthly_flattened(PFE_2015,PFE_df,30)

In [14]:
PFE_2003_labels_df = pd.Series(PFE_2003_labels).to_frame("Label")
PFE_2015_labels_df = pd.Series(PFE_2015_labels).to_frame("Label")

In [15]:
#CREATE DATAFRAME FROM FLATTENED DICTIONARY OF ARRAYS FOR TRAINING AND TEST DATA
PFE_2003_flat_df = pd.DataFrame.from_dict(PFE_2003_flattened).T
PFE_2015_flat_df = pd.DataFrame.from_dict(PFE_2015_flattened).T

In [16]:
#JOIN THE LABEL DATAFRAME AND THE FLATTENED DATAFRAME ON THE INDEX WHICH IS THE DATE
PFE_2003_flat_df = PFE_2003_flat_df.merge(PFE_2003_labels_df, left_index=True, right_index=True)

PFE_2015_flat_df  = PFE_2015_flat_df.merge(PFE_2015_labels_df, left_index=True, right_index=True)

In [18]:
y_test_1 = PFE_2003_flat_df.Label

X_test_1 = PFE_2003_flat_df.reset_index(drop=True)

,0,1,2,3,4,5,6,7,8,9,...,351,352,353,354,355,356,357,358,359,Label
0,0.498797,0.497033,0.497400,0.483396,0.043859,0.482526,0.597182,0.515563,0.546771,0.305892,...,0.504017,0.050116,0.435220,0.384781,0.502950,0.529820,0.353949,0.0,0.0,0
1,0.461374,0.468986,0.480618,0.475094,0.054900,0.417650,0.489993,0.564833,0.563877,0.323166,...,0.503214,0.035986,0.525708,0.491020,0.495206,0.540299,0.331886,0.0,0.0,1
2,0.530874,0.545577,0.550497,0.539636,0.053273,0.444498,0.471407,0.575749,0.627369,0.344304,...,0.452598,0.062797,0.352820,0.506868,0.557604,0.561103,0.302990,0.0,0.0,0
3,0.509489,0.512945,0.526562,0.512587,0.067865,0.213045,0.365872,0.638885,0.636616,0.311080,...,0.491698,0.046704,0.262644,0.346920,0.555170,0.625828,0.367365,0.0,1.0,1
4,0.532211,0.532902,0.540042,0.525442,0.048235,0.172130,0.195747,0.611435,0.582529,0.353261,...,0.527584,0.069741,0.444683,0.514692,0.588951,0.628910,0.365058,0.0,0.0,1

In [19]:
X_test_1 = X_test_1.drop("Label", axis=1)

In [26]:
y_test_df = pd.DataFrame(y_test_1)

In [21]:
y_test_2 = PFE_2015_flat_df.Label

X_test_2 = PFE_2015_flat_df.reset_index(drop=True)

X_test_2 = X_test_2.drop("Label", axis=1)

In [30]:
y_test_2_df = pd.DataFrame(y_test_2)

In [24]:
X_test_1.head(1)

,0,1,2,3,4,5,6,7,8,9,...,350,351,352,353,354,355,356,357,358,359
0,0.498797,0.497033,0.4974,0.483396,0.043859,0.482526,0.597182,0.515563,0.546771,0.305892,...,0.510055,0.504017,0.050116,0.43522,0.384781,0.50295,0.52982,0.353949,0.0,0.0

In [27]:
y_test_df.head(1)

            Label
2003-02-28      0

In [28]:
X_test_2.head(1)

,0,1,2,3,4,5,6,7,8,9,...,350,351,352,353,354,355,356,357,358,359
0,0.536488,0.533711,0.548021,0.540171,0.089295,0.242191,0.271454,0.633796,0.649253,0.206541,...,0.523261,0.509106,0.070123,0.232018,0.464232,0.582239,0.61427,0.209795,0.0,0.0

In [32]:
y_test_2_df.head(1)

            Label
2015-02-27      1

In [33]:
export_Xtest = X_test_1.to_csv("/Users/fahad/project_repo/data/final/PFE/2003_PFE_X_test.csv ")
export_y_test = y_test_df.to_csv("/Users/fahad/project_repo/data/final/PFE/2003_PFE_y_test.csv")
export_X_test_2 = X_test_2.to_csv("/Users/fahad/project_repo/data/final/PFE/2015_PFE_X_test.csv")
export_y_test_2 = y_test_2_df.to_csv("/Users/fahad/project_repo/data/final/PFE/2015_PFE_y_test.csv")

In [10]:
def labelling(dataframe):
    """This generates labels for the dataframes we wish to predict price.
    A label of 1 suggests an increase in price between months while a label of 0 indicates
    a decrease in price. If the current price is greater than the previous price then a"""
    empty_dict = dict()
    prev_close =0
    counter = 0
    for index,cols in dataframe.iterrows():
        counter +=1
        current_close = cols['Close']
        if float(prev_close) <= float(current_close):
            #signals an increase in price between last month and next month
            empty_dict[index] = 1
        elif float(prev_close) >= float(current_close):
            empty_dict[index]=0

        #reassign prev close to the current close     
        prev_close = current_close
    
    return empty_dict

In [11]:
def get_ndays_monthly_flattened(dataframe_period_end,dataframe_subperiod,n):
    """returns a dictionary which contains key value pair of the month-end date as key and
    value is the proceeding n days. Returns it as a dictionary of dataframes.
    dataframe period end refers to the dataframe which will act as the period end i.e monthly end date
    sub_period dataframe refers to the dataframe with the preceeding n days, i.e daily"""
    empty_dict = dict()
    count = 0
    for end in dataframe_period_end.index:
#         print ("month end/:%s" % end)
        
        month_key = dataframe_period_end.index[count+1]
        
#         print ("month key:%s" % month_key)
        
        last_index = dataframe_period_end.index[-1]
        
#         print ("last index:%s " % last_index)
        
        if (month_key != last_index):
            temp_df = dataframe_subperiod.loc[dataframe_subperiod['Date']<end].head(n)
#             print ("\n")
#             print (temp_df.head(5))
            temp_df = temp_df.drop(['Date'], axis=1)
            
            if (len(temp_df.values.flatten())==360):
                empty_dict[month_key]= temp_df.values.flatten()
                count +=1      
            else:
                pass

        else:
            pass
       
    return empty_dict