In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import csv
from pandas.tseries.offsets import MonthEnd
from datetime import datetime, timedelta, date
import requests
import json 
import ta

In [2]:
#assign dates to dataframe index
MAR_df = pd.read_csv("/Users/fahad/project_repo/data/final/MAR/MAR_normalised.csv", index_col=0)
dates = MAR_df.index
MAR_df['Date'] =dates

In [3]:
MAR_df

,Open,High,Low,Close,Volume,RSI,MACD,Ichimoku_Span_A,Ichimoku_Span_B,ATR,BB_High_Indicator,BB_Low_Indicator,Date
2019-08-15,0.857627,0.853757,0.848034,0.845535,0.010445,0.516367,0.242676,0.315166,0.318182,0.168882,0.0,0.0,2019-08-15
2019-08-14,0.868454,0.873202,0.845211,0.843985,0.086897,0.000000,0.242317,0.315166,0.318182,0.227245,0.0,0.0,2019-08-14
2019-08-13,0.867202,0.882741,0.873300,0.885018,0.063795,1.000000,0.259781,0.315166,0.318182,0.290361,0.0,0.0,2019-08-13
2019-08-12,0.874641,0.871881,0.872037,0.867306,0.096360,0.674638,0.252524,0.315166,0.318182,0.298979,0.0,0.0,2019-08-12
2019-08-09,0.875661,0.880907,0.871219,0.885387,0.096318,0.773852,0.260105,0.315166,0.318182,0.315904,0.0,0.0,2019-08-09
2019-08-08,0.859247,0.866818,0.859999,0.869742,0.065707,0.606170,0.250040,0.315166,0.318182,0.344609,0.0,0.0,2019-08-08
2019-08-07,0.838330,0.851042,0.834361,0.851144,0.103041,0.467294,0.229608,0.315166,0.318182,0.388714,0.0,0.0,2019-08-07
2019-08-06,0.840613,0.877018,0.845731,0.856089,0.172594,0.504425,0.224125,0.315166,0.318182,0.437279,0.0,0.0,2019-08-06
2019-08-05,0.895927,0.892212,0.872185,0.869742,0.136492,0.595833,0.234495,0.315166,0.318182,0.480810,0.0,0.0,2019-08-05
2019-08-02,0.915593,0.912166,0.913725,0.911365,0.039832,0.761136,0.279274,0.315166,0.318182,0.532637,0.0,0.0,2019-08-02
2019-08-01,0.932017,0.936014,0.921528,0.917934,0.047796,0.778640,0.308194,0.315166,0.318182,0.549403,0.0,0.0,2019-08-01
2019-07-31,0.946675,0.941444,0.931188,0.934096,0.061050,0.817944,0.336378,0.315166,0.318182,0.563004,0.0,0.0,2019-07-31
2019-07-30,0.941887,0.943132,0.946645,0.947011,0.032748,0.844754,0.359678,0.315166,0.318182,0.549917,0.0,0.0,2019-07-30
2019-07-29,0.939015,0.944086,0.943524,0.950111,0.040544,0.851035,0.368659,0.315166,0.318182,0.534223,0.0,0.0,2019-07-29
2019-07-26,0.948958,0.942251,0.946942,0.943026,0.046226,0.782118,0.357472,0.315166,0.318182,0.510333,0.0,0.0,2019-07-26
2019-07-25,0.936952,0.945186,0.942409,0.946347,0.053736,0.792634,0.346139,0.315166,0.318182,0.501402,0.0,0.0,2019-07-25
2019-07-24,0.940046,0.936308,0.930817,0.939483,0.069408,0.720536,0.323612,0.315166,0.318182,0.500194,0.0,0.0,2019-07-24
2019-07-23,0.919717,0.938876,0.918630,0.946125,0.095554,0.749322,0.310984,0.315166,0.318182,0.522690,0.0,0.0,2019-07-23
2019-07-22,0.921043,0.916202,0.913279,0.911956,0.081968,0.484273,0.256618,0.315166,0.318182,0.550532,0.0,0.0,2019-07-22
2019-07-19,0.941150,0.934106,0.929925,0.924280,0.060965,0.554652,0.235080,0.315166,0.318182,0.561560,0.0,0.0,2019-07-19
2019-07-18,0.944465,0.938656,0.937728,0.939557,0.063195,0.628787,0.238760,0.315166,0.318182,0.558023,0.0,0.0,2019-07-18
2019-07-17,0.968476,0.961287,0.956082,0.950185,0.045955,0.673500,0.252297,0.315166,0.318182,0.568046,0.0,0.0,2019-07-17
2019-07-16,0.961497,0.963531,0.966857,0.970258,0.036308,0.743321,0.283283,0.315166,0.318182,0.562471,0.0,0.0,2019-07-16
2019-07-15,0.954776,0.953552,0.954076,0.961550,0.065945,0.677415,0.286924,0.315166,0.902329,0.558344,0.0,0.0,2019-07-15
2019-07-12,0.955881,0.952598,0.959724,0.959852,0.037920,0.664171,0.282239,0.315166,0.911446,0.529058,0.0,0.0,2019-07-12
2019-07-11,0.956029,0.948929,0.952738,0.955055,0.048817,0.624366,0.268483,0.315166,0.916667,0.511180,0.0,0.0,2019-07-11
2019-07-10,0.935258,0.944306,0.940106,0.952620,0.080033,0.603189,0.252813,0.883708,0.916667,0.508355,0.0,0.0,2019-07-10
2019-07-09,0.929366,0.929557,0.931560,0.937491,0.073062,0.485224,0.219872,0.892551,0.916667,0.516491,0.0,0.0,2019-07-09
2019-07-08,0.952272,0.945186,0.947685,0.950627,0.043003,0.574925,0.215655,0.897615,0.916667,0.504364,0.0,0.0,2019-07-08
2019-07-05,0.946012,0.948415,0.944817,0.955867,0.048049,0.607025,0.219125,0.897615,0.910803,0.497382,0.0,0.0,2019-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999-09-27,0.138013,0.143601,0.142662,0.141683,0.071197,0.408724,0.230474,0.148369,0.140474,0.094333,0.0,0.0,1999-09-27
1999-09-24,0.135725,0.133974,0.136160,0.135225,0.017020,0.325976,0.217822,0.146421,0.140474,0.094714,0.0,1.0,1999-09-24
1999-09-23,0.139390,0.139478,0.137549,0.136605,0.032336,0.359583,0.213480,0.146665,0.140474,0.098347,0.0,0.0,1999-09-23
1999-09-22,0.142616,0.139932,0.139875,0.138915,0.021256,0.416200,0.216019,0.147761,0.140474,0.100081,0.0,0.0,1999-09-22
1999-09-21,0.145835,0.141767,0.143585,0.142605,0.034983,0.498952,0.224845,0.148005,0.140474,0.100865,0.0,0.0,1999-09-21
1999-09-20,0.151810,0.147733,0.147767,0.146753,0.010597,0.578094,0.237868,0.148978,0.140474,0.105699,0.0,0.0,1999-09-20
1999-09-17,0.149061,0.148650,0.152880,0.151830,0.056627,0.656821,0.254229,0.148978,0.140474,0.104454,0.0,0.0,1999-09-17
1999-09-16,0.143994,0.146815,0.149628,0.148598,0.010401,0.582701,0.259476,0.148978,0.140474,0.098373,0.0,0.0,1999-09-16
1999-09-15,0.148597,0.146815,0.145448,0.144450,0.010827,0.499285,0.256086,0.148978,0.140474,0.098465,0.0,0.0,1999-09-15
1999-09-14,0.152744,0.149567,0.147767,0.146753,0.036412,0.544093,0.256995,0.148978,0.140474,0.103471,0.0,0.0,1999-09-14
1999-09-13,0.153664,0.153691,0.155668,0.154598,0.004704,0.665394,0.268736,0.147395,0.140474,0.111399,0.0,0.0,1999-09-13
1999-09-10,0.155962,0.159657,0.158453,0.157365,0.007875,0.699105,0.279063,0.146421,0.140474,0.115481,0.0,0.0,1999-09-10
1999-09-09,0.157787,0.154608,0.156595,0.155520,0.000806,0.653007,0.281039,0.147024,0.140474,0.108604,0.0,0.0,1999-09-09
1999-09-08,0.160566,0.158277,0.159382,0.158288,0.017939,0.691904,0.284430,0.147024,0.140474,0.108779,0.0,0.0,1999-09-08
1999-09-07,0.162407,0.161029,0.161240,0.160133,0.029595,0.716799,0.287067,0.147998,0.140723,0.108941,0.0,0.0,1999-09-07
1999-09-03,0.156886,0.158739,0.160311,0.159210,0.033540,0.687815,0.284888,0.147634,0.140723,0.103358,0.0,0.0,1999-09-03
1999-09-02,0.156426,0.154608,0.156127,0.155055,0.043856,0.568377,0.274915,0.147026,0.140723,0.099000,0.0,0.0,1999-09-02
1999-09-01,0.160109,0.159657,0.158914,0.157823,0.034388,0.623052,0.270772,0.144227,0.146507,0.103154,0.0,0.0,1999-09-01
1999-08-31,0.156426,0.158739,0.161700,0.160590,0.018299,0.672053,0.270436,0.142523,0.146507,0.100451,0.0,0.0,1999-08-31
1999-08-30,0.165169,0.161029,0.157056,0.155978,0.062254,0.546378,0.261496,0.142523,0.146507,0.105315,0.0,0.0,1999-08-30
1999-08-27,0.170693,0.167449,0.167274,0.166125,0.033615,0.702933,0.269477,0.142523,0.146507,0.121312,0.0,0.0,1999-08-27
1999-08-26,0.175296,0.172953,0.172845,0.171661,0.037142,0.758492,0.280744,0.142523,0.146507,0.127966,1.0,0.0,1999-08-26
1999-08-25,0.175296,0.176602,0.177959,0.176738,0.021513,0.799992,0.292715,0.142523,0.146507,0.130829,1.0,0.0,1999-08-25
1999-08-24,0.177602,0.173415,0.175173,0.173970,0.030312,0.730472,0.292752,0.141913,0.146507,0.123683,0.0,0.0,1999-08-24
1999-08-23,0.168395,0.176622,0.182136,0.180886,0.022263,0.791029,0.299552,0.141913,0.143988,0.122780,1.0,0.0,1999-08-23
1999-08-20,0.170693,0.166994,0.169599,0.168435,0.015020,0.558556,0.281389,0.141913,0.143988,0.131783,0.0,0.0,1999-08-20
1999-08-19,0.164248,0.166532,0.170989,0.169815,0.011483,0.575734,0.268951,0.141913,0.143988,0.122102,0.0,0.0,1999-08-19
1999-08-18,0.167010,0.163304,0.166345,0.165203,0.007477,0.505160,0.251808,0.138505,0.143988,0.117219,0.0,0.0,1999-08-18
1999-08-17,0.167931,0.165615,0.170060,0.168893,0.008203,0.558788,0.244905,0.137897,0.143988,0.112684,0.0,0.0,1999-08-17
1999-08-16,0.169772,0.165615,0.169131,0.167970,0.013732,0.542870,0.237937,0.137897,0.143988,0.103554,0.0,0.0,1999-08-16

In [12]:
MAR_2003 = pd.read_csv("/Users/fahad/project_repo/data/final/MAR/2003_MAR.csv", index_col=0)
MAR_2015 = pd.read_csv("/Users/fahad/project_repo/data/final/MAR/2015_MAR.csv", index_col=0)

In [13]:
#ADD LABELS TO THE TRAINING AND TEST DATAFRAMES AND RETURN DICTIONARIES WITH DATE:LABEL FORMAT
MAR_2003_labels = labelling(MAR_2003)
MAR_2015_labels = labelling(MAR_2015)

In [14]:
MAR_2003_flattened= get_ndays_monthly_flattened(MAR_2003,MAR_df,30)
MAR_2015_flattened= get_ndays_monthly_flattened(MAR_2015,MAR_df,30)

In [15]:
MAR_2003_labels_df = pd.Series(MAR_2003_labels).to_frame("Label")
MAR_2015_labels_df = pd.Series(MAR_2015_labels).to_frame("Label")

In [16]:

#CREATE DATAFRAME FROM FLATTENED DICTIONARY OF ARRAYS FOR TRAINING AND TEST DATA
MAR_2003_flat_df = pd.DataFrame.from_dict(MAR_2003_flattened).T
MAR_2015_flat_df = pd.DataFrame.from_dict(MAR_2015_flattened).T

In [17]:
#JOIN THE LABEL DATAFRAME AND THE FLATTENED DATAFRAME ON THE INDEX WHICH IS THE DATE
MAR_2003_flat_df = MAR_2003_flat_df.merge(MAR_2003_labels_df, left_index=True, right_index=True)

MAR_2015_flat_df  = MAR_2015_flat_df.merge(MAR_2015_labels_df, left_index=True, right_index=True)

In [18]:
y_test_1 = MAR_2003_flat_df.Label

X_test_1 = MAR_2003_flat_df.reset_index(drop=True)

In [19]:
X_test_1 = X_test_1.drop("Label", axis=1)

In [20]:
y_test_df = pd.DataFrame(y_test_1)

In [21]:
y_test_2 = MAR_2015_flat_df.Label

X_test_2 = MAR_2015_flat_df.reset_index(drop=True)

X_test_2 = X_test_2.drop("Label", axis=1)

In [22]:
y_test_2_df = pd.DataFrame(y_test_2)

In [23]:
X_test_1.head(1)

,0,1,2,3,4,5,6,7,8,9,...,350,351,352,353,354,355,356,357,358,359
0,0.14252,0.138454,0.135617,0.134686,0.093343,0.555159,0.277824,0.13165,0.14494,0.081777,...,0.150836,0.149815,0.057822,0.490133,0.214395,0.126528,0.130643,0.065825,0.0,0.0

In [24]:
y_test_df.head(1)

            Label
2003-02-28      0

In [25]:
X_test_2.head(1)

,0,1,2,3,4,5,6,7,8,9,...,350,351,352,353,354,355,356,357,358,359
0,0.473963,0.47351,0.472096,0.4769,0.093629,0.5171,0.202885,0.527322,0.525863,0.356896,...,0.473583,0.470775,0.143505,0.351805,0.227954,0.491711,0.508261,0.250119,0.0,0.0

In [26]:
y_test_2_df.head(1)

            Label
2015-02-27      1

In [28]:
export_Xtest = X_test_1.to_csv("/Users/fahad/project_repo/data/final/MAR/2003_MAR_X_test.csv ")
export_y_test = y_test_df.to_csv("/Users/fahad/project_repo/data/final/MAR/2003_MAR_y_test.csv")
export_X_test_2 = X_test_2.to_csv("/Users/fahad/project_repo/data/final/MAR/2015_MAR_X_test.csv")
export_y_test_2 = y_test_2_df.to_csv("/Users/fahad/project_repo/data/final/MAR/2015_MAR_y_test.csv")

In [8]:
def labelling(dataframe):
    """This generates labels for the dataframes we wish to predict price.
    A label of 1 suggests an increase in price between months while a label of 0 indicates
    a decrease in price. If the current price is greater than the previous price then a"""
    empty_dict = dict()
    prev_close =0
    counter = 0
    for index,cols in dataframe.iterrows():
        counter +=1
        current_close = cols['Close']
        if float(prev_close) <= float(current_close):
            #signals an increase in price between last month and next month
            empty_dict[index] = 1
        elif float(prev_close) >= float(current_close):
            empty_dict[index]=0

        #reassign prev close to the current close     
        prev_close = current_close
    
    return empty_dict

In [7]:
def get_ndays_monthly_flattened(dataframe_period_end,dataframe_subperiod,n):
    """returns a dictionary which contains key value pair of the month-end date as key and
    value is the proceeding n days. Returns it as a dictionary of dataframes.
    dataframe period end refers to the dataframe which will act as the period end i.e monthly end date
    sub_period dataframe refers to the dataframe with the preceeding n days, i.e daily"""
    empty_dict = dict()
    count = 0
    for end in dataframe_period_end.index:
#         print ("month end/:%s" % end)
        
        month_key = dataframe_period_end.index[count+1]
        
#         print ("month key:%s" % month_key)
        
        last_index = dataframe_period_end.index[-1]
        
#         print ("last index:%s " % last_index)
        
        if (month_key != last_index):
            temp_df = dataframe_subperiod.loc[dataframe_subperiod['Date']<end].head(n)
#             print ("\n")
#             print (temp_df.head(5))
            temp_df = temp_df.drop(['Date'], axis=1)
            
            if (len(temp_df.values.flatten())==360):
                empty_dict[month_key]= temp_df.values.flatten()
                count +=1      
            else:
                pass

        else:
            pass
       
    return empty_dict