In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import csv
from pandas.tseries.offsets import MonthEnd
from datetime import datetime, timedelta, date
import requests
import json 
import ta

In [2]:
#assign dates to dataframe index
GOOG_df = pd.read_csv("/Users/fahad/project_repo/data/final/GOOG/GOOG_normalised.csv", index_col=0)
dates = GOOG_df.index
GOOG_df['Date'] =dates

In [3]:
GOOG_df

,Open,High,Low,Close,Volume,RSI,MACD,Ichimoku_Span_A,Ichimoku_Span_B,ATR,BB_High_Indicator,BB_Low_Indicator,Date
2019-08-15,0.909766,0.908420,0.914965,0.904917,0.005283,0.557772,0.467490,0.344340,0.352485,0.196137,0.0,0.0,2019-08-15
2019-08-14,0.920226,0.913466,0.913208,0.900393,0.019019,0.000000,0.465589,0.344340,0.352485,0.212216,0.0,0.0,2019-08-14
2019-08-13,0.916266,0.931785,0.922170,0.927038,0.015588,0.972440,0.486225,0.344340,0.352485,0.256932,0.0,0.0,2019-08-13
2019-08-12,0.922595,0.915783,0.919062,0.908811,0.012057,0.576077,0.471184,0.344340,0.352485,0.281324,0.0,0.0,2019-08-12
2019-08-09,0.937930,0.931059,0.932211,0.919556,0.012817,0.693182,0.477485,0.344340,0.352485,0.303302,0.0,0.0,2019-08-09
2019-08-08,0.925551,0.931971,0.923451,0.933121,0.017691,0.794648,0.496843,0.344340,0.352485,0.328144,0.0,0.0,2019-08-08
2019-08-07,0.903641,0.910523,0.904250,0.908230,0.017404,0.526725,0.467687,0.344340,0.352485,0.387674,0.0,0.0,2019-08-07
2019-08-06,0.909611,0.911746,0.912765,0.904966,0.020616,0.501160,0.447511,0.344340,0.352485,0.387571,0.0,0.0,2019-08-06
2019-08-05,0.915106,0.907936,0.896466,0.890722,0.031376,0.402736,0.415099,0.344340,0.352485,0.411285,0.0,0.0,2019-08-05
2019-08-02,0.940176,0.933497,0.936516,0.924388,0.019837,0.651357,0.457566,0.344340,0.352485,0.463939,0.0,0.0,2019-08-02
2019-08-01,0.950980,0.955465,0.950287,0.936523,0.020484,0.710163,0.503453,0.344340,0.352485,0.490093,0.0,0.0,2019-08-01
2019-07-31,0.958353,0.955377,0.951964,0.942719,0.020811,0.738321,0.538688,0.344340,0.352485,0.492544,0.0,0.0,2019-07-31
2019-07-30,0.960321,0.956079,0.964715,0.949554,0.017513,0.768960,0.567350,0.344340,0.352485,0.482167,0.0,0.0,2019-07-30
2019-07-29,0.973093,0.966171,0.968761,0.961083,0.026847,0.816269,0.599926,0.344340,0.352485,0.478885,0.0,0.0,2019-07-29
2019-07-26,0.959203,0.980849,0.965257,0.969970,0.058133,0.848670,0.628218,0.344340,0.352485,0.506281,0.0,0.0,2019-07-26
2019-07-25,0.888795,0.880856,0.880693,0.874402,0.026679,0.362160,0.440563,0.344340,0.352485,0.669954,0.0,0.0,2019-07-25
2019-07-24,0.883961,0.882713,0.885674,0.878999,0.019167,0.385392,0.336535,0.344340,0.352485,0.645049,0.0,0.0,2019-07-24
2019-07-23,0.893842,0.885055,0.889622,0.885786,0.013156,0.421830,0.293924,0.344340,0.352485,0.618920,0.0,0.0,2019-07-23
2019-07-22,0.885227,0.878878,0.883418,0.879209,0.015674,0.399536,0.262867,0.344340,0.352485,0.605460,0.0,0.0,2019-07-22
2019-07-19,0.897264,0.888478,0.887881,0.872770,0.019862,0.377024,0.241017,0.344340,0.352485,0.592162,0.0,0.0,2019-07-19
2019-07-18,0.891997,0.885624,0.890385,0.885883,0.015550,0.463367,0.269738,0.344340,0.352485,0.573592,0.0,0.0,2019-07-18
2019-07-17,0.899534,0.894307,0.901087,0.885899,0.014080,0.463475,0.299367,0.344340,0.352485,0.548620,0.0,0.0,2019-07-17
2019-07-16,0.895475,0.894485,0.900455,0.891740,0.014914,0.505750,0.341645,0.344340,0.352485,0.526988,0.0,0.0,2019-07-16
2019-07-15,0.896178,0.888220,0.895859,0.889122,0.010855,0.489346,0.370349,0.344340,0.963645,0.507844,0.0,0.0,2019-07-15
2019-07-12,0.893834,0.885410,0.895350,0.884727,0.010373,0.460414,0.385077,0.344340,0.965462,0.485948,0.0,0.0,2019-07-12
2019-07-11,0.893230,0.890036,0.896007,0.884170,0.014389,0.456464,0.399478,0.344340,0.975492,0.468651,0.0,0.0,2019-07-11
2019-07-10,0.883406,0.881139,0.888941,0.881156,0.014559,0.433280,0.407177,0.943326,0.975492,0.452196,0.0,0.0,2019-07-10
2019-07-09,0.867548,0.869748,0.869408,0.868513,0.016024,0.347767,0.387152,0.945092,0.975492,0.468479,0.0,0.0,2019-07-09
2019-07-08,0.878470,0.868165,0.872724,0.861662,0.014885,0.309568,0.364895,0.954843,0.975593,0.454443,0.0,0.0,2019-07-08
2019-07-05,0.872447,0.873735,0.876770,0.873974,0.015223,0.459089,0.389428,0.954843,0.970768,0.444507,0.0,0.0,2019-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2004-09-30,0.012492,0.012291,0.013507,0.011908,0.167391,0.251148,0.454764,0.013994,0.010248,0.034932,0.0,0.0,2004-09-30
2004-09-29,0.011190,0.013384,0.012375,0.012504,0.371406,0.306620,0.459360,0.014122,0.010248,0.035522,0.0,0.0,2004-09-29
2004-09-28,0.008994,0.010320,0.009914,0.010806,0.205995,0.253169,0.459737,0.016520,0.010248,0.037699,0.0,0.0,2004-09-28
2004-09-27,0.008286,0.007698,0.008928,0.007345,0.085925,0.179567,0.452727,0.016520,0.010248,0.038302,0.0,0.0,2004-09-27
2004-09-24,0.008847,0.008993,0.009730,0.007976,0.110971,0.233580,0.452495,0.016520,0.010248,0.036340,0.0,0.0,2004-09-24
2004-09-23,0.007993,0.008401,0.008610,0.008375,0.103815,0.269115,0.455931,0.016520,0.010248,0.034338,0.0,0.0,2004-09-23
2004-09-22,0.007407,0.007211,0.008524,0.007393,0.092195,0.241448,0.457800,0.016520,0.010248,0.031226,0.0,0.0,2004-09-22
2004-09-21,0.008388,0.007513,0.008810,0.007176,0.087905,0.235271,0.460666,0.016871,0.010248,0.027474,0.0,0.0,2004-09-21
2004-09-20,0.007224,0.007987,0.008507,0.007787,0.129296,0.302794,0.466252,0.016871,0.005912,0.025494,0.0,0.0,2004-09-20
2004-09-17,0.006195,0.006334,0.007191,0.007035,0.115220,0.273059,0.469585,0.017299,0.005468,0.024424,0.0,0.0,2004-09-17
2004-09-16,0.005349,0.005655,0.006414,0.005618,0.112709,0.225057,0.469539,0.016393,0.005018,0.023453,0.0,0.0,2004-09-16
2004-09-15,0.004625,0.005023,0.005821,0.004825,0.130323,0.202114,0.469052,0.011705,0.005018,0.021134,0.0,0.0,2004-09-15
2004-09-14,0.003360,0.004126,0.004427,0.004620,0.131733,0.196139,0.469890,0.011272,0.005018,0.019905,0.0,0.0,2004-09-14
2004-09-13,0.003026,0.002683,0.004293,0.003014,0.095396,0.154834,0.467742,0.011272,0.004789,0.018622,0.0,0.0,2004-09-13
2004-09-10,0.000980,0.001938,0.002183,0.002141,0.105803,0.136759,0.465805,0.010682,0.004789,0.018348,0.0,0.0,2004-09-10
2004-09-09,0.001359,0.000390,0.002060,0.000926,0.049350,0.115172,0.463186,0.010682,0.003653,0.016628,0.0,0.0,2004-09-09
2004-09-08,0.000630,0.000519,0.001856,0.000922,0.060597,0.115102,0.463543,0.010459,0.003653,0.013622,0.0,0.0,2004-09-08
2004-09-07,0.000740,0.000105,0.001492,0.000632,0.071090,0.109613,0.464989,0.010459,0.003653,0.010955,0.0,0.0,2004-09-07
2004-09-03,0.000716,0.000000,0.001374,0.000000,0.062628,0.097871,0.466126,0.007828,0.003653,0.008267,0.0,0.0,2004-09-03
2004-09-02,0.000000,0.000253,0.001218,0.000604,0.183955,0.205363,0.470337,0.004856,0.003653,0.006563,0.0,0.0,2004-09-02
2004-09-01,0.001428,0.000495,0.001517,0.000097,0.111151,0.186290,0.473258,0.004856,0.003398,0.004878,0.0,0.0,2004-09-01
2004-08-31,0.001265,0.000792,0.002535,0.000950,0.059773,0.328241,0.478865,0.004856,0.003398,0.003439,0.0,0.0,2004-08-31
2004-08-30,0.002477,0.001508,0.002473,0.000805,0.063168,0.318699,0.483150,0.004513,0.002662,0.002119,0.0,0.0,2004-08-30
2004-08-27,0.003624,0.002767,0.003978,0.002471,0.075524,0.540453,0.491217,0.003869,0.002662,0.003345,0.0,0.0,2004-08-27
2004-08-26,0.002343,0.002498,0.003557,0.003179,0.086276,0.609527,0.498601,0.003660,0.002074,0.001882,0.0,0.0,2004-08-26
2004-08-25,0.002347,0.002518,0.003238,0.002411,0.111763,0.529841,0.501128,0.002945,0.000749,0.001174,0.0,0.0,2004-08-25
2004-08-24,0.004902,0.003965,0.003111,0.001956,0.185522,0.486428,0.501245,0.002553,0.000218,0.003580,0.0,0.0,2004-08-24
2004-08-23,0.004702,0.004722,0.005351,0.003779,0.222151,0.659329,0.505894,0.001981,0.000218,0.006268,0.0,0.0,2004-08-23
2004-08-20,0.000740,0.002952,0.001856,0.003340,0.277886,0.612591,0.506970,0.000516,0.000046,0.008991,0.0,0.0,2004-08-20
2004-08-19,0.000329,0.000933,0.000000,0.000133,0.543577,0.383317,0.498214,0.000000,0.000000,0.014223,0.0,0.0,2004-08-19

In [4]:
GOOG_2006 = pd.read_csv("/Users/fahad/project_repo/data/final/GOOG/2006_GOOG.csv", index_col=0)
GOOG_2015 = pd.read_csv("/Users/fahad/project_repo/data/final/GOOG/2015_GOOG.csv", index_col=0)

In [8]:
#ADD LABELS TO THE TRAINING AND TEST DATAFRAMES AND RETURN DICTIONARIES WITH DATE:LABEL FORMAT
GOOG_2006_labels = labelling(GOOG_2006)
GOOG_2015_labels = labelling(GOOG_2015)

In [9]:
GOOG_2006_flattened= get_ndays_monthly_flattened(GOOG_2006,GOOG_df,30)
GOOG_2015_flattened= get_ndays_monthly_flattened(GOOG_2015,GOOG_df,30)

In [10]:
GOOG_2006_labels_df = pd.Series(GOOG_2006_labels).to_frame("Label")
GOOG_2015_labels_df = pd.Series(GOOG_2015_labels).to_frame("Label")

In [11]:

#CREATE DATAFRAME FROM FLATTENED DICTIONARY OF ARRAYS FOR TRAINING AND TEST DATA
GOOG_2006_flat_df = pd.DataFrame.from_dict(GOOG_2006_flattened).T
GOOG_2015_flat_df = pd.DataFrame.from_dict(GOOG_2015_flattened).T

In [12]:
#JOIN THE LABEL DATAFRAME AND THE FLATTENED DATAFRAME ON THE INDEX WHICH IS THE DATE
GOOG_2006_flat_df = GOOG_2006_flat_df.merge(GOOG_2006_labels_df, left_index=True, right_index=True)

GOOG_2015_flat_df  = GOOG_2015_flat_df.merge(GOOG_2015_labels_df, left_index=True, right_index=True)

In [13]:
y_test_1 = GOOG_2006_flat_df.Label

X_test_1 = GOOG_2006_flat_df.reset_index(drop=True)

In [14]:
X_test_1 = X_test_1.drop("Label", axis=1)

In [15]:
y_test_df = pd.DataFrame(y_test_1)

In [16]:
y_test_2 = GOOG_2015_flat_df.Label

X_test_2 = GOOG_2015_flat_df.reset_index(drop=True)

X_test_2 = X_test_2.drop("Label", axis=1)

In [17]:
y_test_2_df = pd.DataFrame(y_test_2)

In [18]:
X_test_1.head(1)

,0,1,2,3,4,5,6,7,8,9,...,350,351,352,353,354,355,356,357,358,359
0,0.134252,0.133338,0.134515,0.131524,0.208814,0.865392,0.600195,0.092773,0.102143,0.153339,...,0.13104,0.129805,0.146957,0.448294,0.405223,0.111678,0.102916,0.120989,0.0,0.0

In [19]:
y_test_df.head(1)

            Label
2006-02-28      0

In [20]:
X_test_2.head(1)

,0,1,2,3,4,5,6,7,8,9,...,350,351,352,353,354,355,356,357,358,359
0,0.376934,0.371728,0.372098,0.372319,0.050627,0.311516,0.410325,0.414796,0.415671,0.247322,...,0.362086,0.359982,0.047936,0.267297,0.416489,0.393415,0.406913,0.234739,0.0,0.0

In [21]:
y_test_2_df.head(1)

            Label
2015-02-27      1

In [22]:
export_Xtest = X_test_1.to_csv("/Users/fahad/project_repo/data/final/GOOG/2006_GOOG_X_test.csv ")
export_y_test = y_test_df.to_csv("/Users/fahad/project_repo/data/final/GOOG/2006_GOOG_y_test.csv")
export_X_test_2 = X_test_2.to_csv("/Users/fahad/project_repo/data/final/GOOG/2015_GOOG_X_test.csv")
export_y_test_2 = y_test_2_df.to_csv("/Users/fahad/project_repo/data/final/GOOG/2015_GOOG_y_test.csv")

In [6]:
def labelling(dataframe):
    """This generates labels for the dataframes we wish to predict price.
    A label of 1 suggests an increase in price between months while a label of 0 indicates
    a decrease in price. If the current price is greater than the previous price then a"""
    empty_dict = dict()
    prev_close =0
    counter = 0
    for index,cols in dataframe.iterrows():
        counter +=1
        current_close = cols['Close']
        if float(prev_close) <= float(current_close):
            #signals an increase in price between last month and next month
            empty_dict[index] = 1
        elif float(prev_close) >= float(current_close):
            empty_dict[index]=0

        #reassign prev close to the current close     
        prev_close = current_close
    
    return empty_dict

In [7]:
def get_ndays_monthly_flattened(dataframe_period_end,dataframe_subperiod,n):
    """returns a dictionary which contains key value pair of the month-end date as key and
    value is the proceeding n days. Returns it as a dictionary of dataframes.
    dataframe period end refers to the dataframe which will act as the period end i.e monthly end date
    sub_period dataframe refers to the dataframe with the preceeding n days, i.e daily"""
    empty_dict = dict()
    count = 0
    for end in dataframe_period_end.index:
#         print ("month end/:%s" % end)
        
        month_key = dataframe_period_end.index[count+1]
        
#         print ("month key:%s" % month_key)
        
        last_index = dataframe_period_end.index[-1]
        
#         print ("last index:%s " % last_index)
        
        if (month_key != last_index):
            temp_df = dataframe_subperiod.loc[dataframe_subperiod['Date']<end].head(n)
#             print ("\n")
#             print (temp_df.head(5))
            temp_df = temp_df.drop(['Date'], axis=1)
            
            if (len(temp_df.values.flatten())==360):
                empty_dict[month_key]= temp_df.values.flatten()
                count +=1      
            else:
                pass

        else:
            pass
       
    return empty_dict