In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import csv
from pandas.tseries.offsets import MonthEnd
from datetime import datetime, timedelta, date
import requests
import json 
import ta

In [4]:
#data with feature engineering
fields = ['Date', 'Open','High','Low','Close','Volume','RSI','MACD','Ichimoku_Span_A','Ichimoku_Span_B','ATR',
         'BB_High_Indicator','BB_Low_Indicator']
AAPL_df = pd.read_csv(r"/Users/fahad/project_repo/data/interim/AAPL.csv", usecols=fields)

In [5]:
#daily data with indicators and OHLC, drop the OHLC for this dataset
AAPL_df.head()
AAPL_df = AAPL_df.drop(['Open','High','Low','Close','Volume'], axis=1)

In [6]:
#/Users/fahad/project_repo/data/final/Tech/AAPL

In [7]:
AAPL_df.head()

,Date,RSI,MACD,Ichimoku_Span_A,Ichimoku_Span_B,ATR,BB_High_Indicator,BB_Low_Indicator
0,2019-07-10,0.501517,0.236025,0.21848,0.225426,0.109922,0.0,0.0
1,2019-07-09,0.000000,0.235805,0.21848,0.225426,0.108859,0.0,0.0
2,2019-07-08,0.000000,0.235560,0.21848,0.225426,0.105483,0.0,0.0
3,2019-07-05,0.628447,0.236711,0.21848,0.225426,0.105949,0.0,0.0
4,2019-07-03,0.639678,0.237131,0.21848,0.225426,0.100623,0.0,0.0

In [8]:
#monthly data split into various training and test intervals
AAPL_98_train = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/1998_AAPL_train.csv", index_col=1)

AAPL_98_test = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/1998_AAPL_test.csv", index_col=1)

AAPL_02_train = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/2002_AAPL_train.csv", index_col=1)

AAPL_02_test = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/2002_AAPL_test.csv", index_col=1)

AAPL_06_train = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/2006_AAPL_train.csv", index_col=1)

AAPL_06_test = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/2006_AAPL_test.csv", index_col=1)

AAPL_10_train = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/2010_AAPL_train.csv", index_col=1)

AAPL_10_test = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/2010_AAPL_test.csv", index_col=1)

AAPL_14_train = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/2014_AAPL_train.csv", index_col=1)

AAPL_14_test = pd.read_csv("/Users/fahad/project_repo/data/final/AAPL/2014_AAPL_test.csv", index_col=1)

In [9]:
#ADD LABELS TO THE TRAINING AND TEST DATAFRAMES AND RETURN DICTIONARIES WITH DATE:LABEL FORMAT
AAPL_98_train_labels = labelling(AAPL_98_train)

AAPL_98_test_labels  = labelling(AAPL_98_test)

AAPL_02_train_labels = labelling(AAPL_02_train)

AAPL_02_test_labels  = labelling(AAPL_02_test)

AAPL_06_train_labels = labelling(AAPL_06_train)

AAPL_06_test_labels  = labelling(AAPL_06_test)

AAPL_10_train_labels = labelling(AAPL_10_train)

AAPL_10_test_labels  = labelling(AAPL_10_test)

AAPL_14_train_labels = labelling(AAPL_14_train)

AAPL_14_test_labels  = labelling(AAPL_14_test)

In [10]:
#GET 30 DAY PERIODS FOR EACH MONTH AND CREATE DICTIONARY FOR 30DAYS PRIOR TO EACH DATE 
AAPL_98_train_flattened= get_ndays_monthly_flattened(AAPL_98_train,AAPL_df,30)

AAPL_98_test_flattened= get_ndays_monthly_flattened(AAPL_98_test,AAPL_df,30)

AAPL_02_train_flattened = get_ndays_monthly_flattened(AAPL_02_train,AAPL_df,30)

AAPL_02_test_flattened = get_ndays_monthly_flattened(AAPL_02_test,AAPL_df,30)

AAPL_06_train_flattened = get_ndays_monthly_flattened(AAPL_06_train,AAPL_df,30)

AAPL_06_test_flattened = get_ndays_monthly_flattened(AAPL_06_test,AAPL_df,30)

AAPL_10_train_flattened = get_ndays_monthly_flattened(AAPL_10_train,AAPL_df,30)

AAPL_10_test_flattened = get_ndays_monthly_flattened(AAPL_10_test,AAPL_df,30)

AAPL_14_train_flattened = get_ndays_monthly_flattened(AAPL_14_train,AAPL_df,30)

AAPL_14_test_flattened = get_ndays_monthly_flattened(AAPL_14_test,AAPL_df,30)

In [11]:
#assign labels to a dataframe object
AAPL_98_train_labels_df = pd.Series(AAPL_98_train_labels).to_frame("Label")

AAPL_98_test_labels_df  =  pd.Series(AAPL_98_test_labels).to_frame("Label")

AAPL_02_train_labels_df =  pd.Series(AAPL_02_train_labels).to_frame("Label")

AAPL_02_test_labels_df =  pd.Series(AAPL_02_test_labels).to_frame("Label")

AAPL_06_train_labels_df =  pd.Series(AAPL_06_train_labels).to_frame("Label")

AAPL_06_test_labels_df =  pd.Series(AAPL_06_test_labels).to_frame("Label")

AAPL_10_train_labels_df =  pd.Series(AAPL_10_train_labels).to_frame("Label")

AAPL_10_test_labels_df =  pd.Series(AAPL_10_test_labels).to_frame("Label")

AAPL_14_train_labels_df =  pd.Series(AAPL_14_train_labels).to_frame("Label")

AAPL_14_test_labels_df =  pd.Series(AAPL_14_test_labels).to_frame("Label")

In [12]:
#CREATE DATAFRAME FROM FLATTENED DICTIONARY OF ARRAYS FOR TRAINING AND TEST DATA
AAPL_98_train_flat_df = pd.DataFrame.from_dict(AAPL_98_train_flattened).T

AAPL_98_test_flat_df = pd.DataFrame.from_dict(AAPL_98_test_flattened).T

AAPL_02_train_flat_df = pd.DataFrame.from_dict(AAPL_02_train_flattened).T

AAPL_02_test_flat_df = pd.DataFrame.from_dict(AAPL_02_test_flattened).T

AAPL_06_train_flat_df = pd.DataFrame.from_dict(AAPL_06_train_flattened).T

AAPL_06_test_flat_df = pd.DataFrame.from_dict(AAPL_06_test_flattened).T

AAPL_10_train_flat_df = pd.DataFrame.from_dict(AAPL_10_train_flattened).T

AAPL_10_test_flat_df = pd.DataFrame.from_dict(AAPL_10_test_flattened).T

AAPL_14_train_flat_df = pd.DataFrame.from_dict(AAPL_14_train_flattened).T

AAPL_14_test_flat_df = pd.DataFrame.from_dict(AAPL_14_test_flattened).T

In [13]:

#JOIN THE LABEL DATAFRAME AND THE FLATTENED DATAFRAME ON THE INDEX WHICH IS THE DATE
AAPL_98_train_flat_df = AAPL_98_train_flat_df.merge(AAPL_98_train_labels_df, left_index=True, right_index=True)

AAPL_98_test_flat_df  = AAPL_98_test_flat_df.merge(AAPL_98_test_labels_df, left_index=True, right_index=True)

AAPL_02_train_flat_df = AAPL_02_train_flat_df.merge(AAPL_02_train_labels_df, left_index=True, right_index=True)

AAPL_02_test_flat_df = AAPL_02_test_flat_df.merge(AAPL_02_test_labels_df, left_index=True, right_index=True)

AAPL_06_train_flat_df = AAPL_06_train_flat_df.merge(AAPL_06_train_labels_df, left_index=True, right_index=True)

AAPL_06_test_flat_df =AAPL_06_test_flat_df.merge(AAPL_06_test_labels_df, left_index=True, right_index=True)

AAPL_10_train_flat_df =AAPL_10_train_flat_df.merge(AAPL_10_train_labels_df, left_index=True, right_index=True)

AAPL_10_test_flat_df =AAPL_10_test_flat_df.merge(AAPL_10_test_labels_df, left_index=True, right_index=True)

AAPL_14_train_flat_df =AAPL_14_train_flat_df.merge(AAPL_14_train_labels_df, left_index=True, right_index=True)

AAPL_14_test_flat_df =AAPL_14_test_flat_df.merge(AAPL_14_test_labels_df, left_index=True, right_index=True)

In [14]:
AAPL_98_train_flat_df.head()

,0,1,2,3,4,5,6,7,8,9,...,201,202,203,204,205,206,207,208,209,Label
1998-03-31,0.397406,0.233885,0.020406,0.021966,0.027052,0.0,0.0,0.315975,0.233583,0.019229,...,0.0,0.0,0.623920,0.239569,0.013663,0.016457,0.011809,0.0,0.0,1
1998-04-30,0.555793,0.237592,0.022901,0.025056,0.017298,0.0,0.0,0.470401,0.237397,0.023184,...,0.0,0.0,0.234613,0.232582,0.019535,0.021912,0.025558,0.0,0.0,0
1998-05-29,0.259360,0.232933,0.022387,0.030078,0.018650,0.0,0.0,0.255223,0.232329,0.021776,...,0.0,0.0,0.503421,0.236594,0.021655,0.022684,0.018755,0.0,0.0,0
1998-06-30,0.521068,0.238408,0.029417,0.033988,0.021081,0.0,0.0,0.431866,0.238399,0.028029,...,0.0,0.0,0.535678,0.236311,0.019791,0.027714,0.021974,0.0,0.0,1
1998-07-31,0.270789,0.230948,0.035523,0.034281,0.036416,0.0,0.0,0.249823,0.231221,0.034840,...,0.0,0.0,0.559621,0.241351,0.025312,0.032929,0.022146,0.0,0.0,1

In [15]:

#export dataframes which are now ready to be used by the model 
AAPL_list_of_names = ['AAPL_98_train_flat_df_Tech', 'AAPL_98_test_flat_df_Tech', 'AAPL_02_train_flat_df_Tech', 'AAPL_02_test_flat_df_Tech'
                     ,'AAPL_06_train_flat_df_Tech','AAPL_06_test_flat_df_Tech','AAPL_10_train_flat_df_Tech','AAPL_10_test_flat_df_Tech',
                     'AAPL_14_train_flat_df_Tech','AAPL_14_test_flat_df_Tech']

AAPL_list = [AAPL_98_train_flat_df, AAPL_98_test_flat_df, AAPL_02_train_flat_df, AAPL_02_test_flat_df,
            AAPL_06_train_flat_df, AAPL_06_test_flat_df, AAPL_10_train_flat_df, AAPL_10_test_flat_df,
            AAPL_14_train_flat_df, AAPL_14_test_flat_df]

for i in range(len(AAPL_list)):
    
    str_name = AAPL_list_of_names[i]
    
    export_AAPL = AAPL_list[i].to_csv("/Users/fahad/project_repo/data/final/Tech/AAPL/{}.csv".format(str_name))

In [2]:
def labelling(dataframe):
    """This generates labels for the dataframes we wish to predict price.
    A label of 1 suggests an increase in price between months while a label of 0 indicates
    a decrease in price. If the current price is greater than the previous price then a"""
    empty_dict = dict()
    prev_close =0
    counter = 0
    for index,cols in dataframe.iterrows():
        counter +=1
        current_close = cols['Close']
        if float(prev_close) <= float(current_close):
            #signals an increase in price between last month and next month
            empty_dict[index] = 1
        elif float(prev_close) >= float(current_close):
            empty_dict[index]=0

        #reassign prev close to the current close     
        prev_close = current_close
    
    return empty_dict

In [3]:
def get_ndays_monthly_flattened(dataframe_period_end,dataframe_subperiod,n):
    """returns a dictionary which contains key value pair of the month-end date as key and
    value is the proceeding n days. Returns it as a dictionary of dataframes.
    dataframe period end refers to the dataframe which will act as the period end i.e monthly end date
    sub_period dataframe refers to the dataframe with the preceeding n days, i.e daily"""
    empty_dict = dict()
    count = 0
    for end in dataframe_period_end.index:
#         print ("month end/:%s" % end)
        
        month_key = dataframe_period_end.index[count+1]
        
#         print ("month key:%s" % month_key)
        
        last_index = dataframe_period_end.index[-1]
        
#         print ("last index:%s " % last_index)
        
        if (month_key != last_index):
            temp_df = dataframe_subperiod.loc[dataframe_subperiod['Date']<end].head(n)
#             print ("\n")
#             print (temp_df.head(5))
            temp_df = temp_df.drop(['Date'], axis=1)
            
            empty_dict[month_key]= temp_df.values.flatten()
            count +=1
        else:
            pass
       
    return empty_dict