In [77]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import csv
from pandas.tseries.offsets import MonthEnd
from datetime import datetime, timedelta, date
import requests
import json 
import datetime as dt
from dateutil import parser

In [78]:
#read in dataframes with MONTHLY data 
MSFT = pd.read_csv(r"/Users/fahad/project_repo/data/external/MSFT_monthly.csv")
AAPL = pd.read_csv(r"/Users/fahad/project_repo/data/external/AAPL_monthly.csv")
AMZN = pd.read_csv(r"/Users/fahad/project_repo/data/external/AMZN_monthly.csv")

MSFT_test = pd.read_csv(r"/Users/fahad/project_repo/data/external/MSFT_monthly.csv")

#GIVE COLUMN NAMES 
MSFT.columns = ['Date','Open','High','Low','Close','Volume']
AAPL.columns = ['Date','Open','High','Low','Close','Volume']
AMZN.columns = ['Date','Open','High','Low','Close','Volume']
MSFT_test.columns = ['Date','Open','High','Low','Close','Volume']

MSFT.Date = pd.to_datetime(MSFT.Date, format='%Y-%m-%d')
AAPL.Date = pd.to_datetime(AAPL.Date, format='%Y-%m-%d')
AMZN.Date = pd.to_datetime(AMZN.Date,format='%Y-%m-%d')

#set date column as the index
MSFT = MSFT.set_index(['Date'])
AAPL = AAPL.set_index(['Date'])
AMZN = AMZN.set_index(['Date'])
# MSFT_test = MSFT_test.set_index(['Date'])

In [114]:
control_dict = {"MSFT":MSFT, "AAPL":AAPL,"AMZN":AMZN}

for key, value in control_dict.items():
    window_split_data(value,6,key)

[1998, 2002, 2006, 2010, 2014, 2018]
            Open   High   Low  Close      Volume       Date
Date
2003-12-31  25.9  27.55  25.5  27.37  1476460838 2003-12-31
              Open    High    Low  Close     Volume       Date
Date
1998-02-27  151.75  160.06  79.37  84.75  215522751 1998-02-27
(71, 6)




            Open   High    Low  Close      Volume       Date
Date
2007-12-31  33.5  36.72  32.63   35.6  1064816680 2007-12-31
             Open   High    Low  Close     Volume       Date
Date
2002-01-31  66.65  70.62  61.33  63.71  680057459 2002-01-31
(72, 6)




             Open   High    Low  Close      Volume       Date
Date
2011-12-30  25.56  26.19  25.16  25.96  1007166159 2011-12-30
             Open   High   Low  Close      Volume       Date
Date
2006-01-31  26.25  28.38  26.1  28.15  1388622280 2006-01-31
(72, 6)




             Open   High    Low  Close     Volume       Date
Date
2015-12-31  54.41  56.85  53.68  55.48  793069538 2015-12-31
             Open   High    Low  Close      Volume       Date
Date
2010-01-29  30.62  31.24  27.66  28.18  1359650501 2010-01-29
(72, 6)




              Open   High     Low   Close     Volume       Date
Date
2019-06-28  123.85  138.4  119.01  133.96  508324017 2019-06-28
             Open   High    Low  Close     Volume       Date
Date
2014-01-31  37.35  37.89  34.63  37.84  930225759 2014-01-31
(66, 6)




[1998, 2002, 2006, 2010, 2014, 2018]
             Open  High    Low  Close    Volume       Date
Date
2003-12-31  21.04  21.9  19.25  21.37  97390600 2003-12-31
            Open   High    Low  Close    Volume       Date
Date
1998-02-27  18.5  23.87  17.37  23.62  65662200 1998-02-27
(71, 6)




              Open    High     Low   Close     Volume       Date
Date
2007-12-31  181.86  202.96  176.99  198.08  616167100 2007-12-31
             Open   High    Low  Close     Volume       Date
Date
2002-01-31  22.05  24.73  20.26  24.72  152060300 2002-01-31
(72, 6)




              Open    High     Low  Close     Volume       Date
Date
2011-12-30  382.54  409.09  377.68  405.0  225233300 2011-12-30
              Open  High    Low  Close     Volume       Date
Date
2006-01-31  72.332  86.4  70.87  75.51  781370400 2006-01-31
(72, 6)




              Open    High     Low   Close     Volume       Date
Date
2015-12-31  118.75  119.86  104.82  105.26  922626259 2015-12-31
              Open    High     Low    Close     Volume       Date
Date
2010-01-29  213.43  215.59  190.25  192.063  541749800 2010-01-29
(72, 6)




             Open    High     Low   Close     Volume       Date
Date
2019-06-28  175.6  201.57  170.27  197.92  515218768 2019-06-28
              Open   High     Low  Close     Volume       Date
Date
2014-01-31  555.68  560.2  493.55  500.6  313069800 2014-01-31
(66, 6)




[1998, 2002, 2006, 2010, 2014, 2018]
            Open   High   Low  Close     Volume       Date
Date
2003-12-31  54.4  54.94  47.0  52.62  193675200 2003-12-31
             Open   High    Low  Close    Volume       Date
Date
1998-02-27  59.38  79.63  57.25   77.0  10885100 1998-02-27
(71, 6)




             Open   High    Low  Close     Volume       Date
Date
2007-12-31  90.03  95.94  83.86  92.64  127062200 2007-12-31
             Open   High   Low  Close     Volume       Date
Date
2002-01-31  10.94  15.77  9.03  14.19  322739200 2002-01-31
(72, 6)




              Open    High     Low  Close     Volume       Date
Date
2011-12-30  191.85  199.66  166.97  173.1  125595200 2011-12-30
             Open   High   Low  Close     Volume       Date
Date
2006-01-31  47.47  48.58  43.1  44.82  123410300 2006-01-31
(72, 6)




              Open    High     Low   Close    Volume       Date
Date
2015-12-31  673.75  696.44  635.27  675.89  90220804 2015-12-31
              Open    High     Low   Close     Volume       Date
Date
2010-01-29  136.25  136.61  118.12  125.41  230861000 2010-01-29
(72, 6)




               Open    High     Low    Close    Volume       Date
Date
2019-06-28  1760.01  1935.2  1672.0  1893.63  74746589 2019-06-28
             Open    High     Low   Close    Volume       Date
Date
2014-01-31  398.8  408.06  357.76  358.69  81011900 2014-01-31
(66, 6)

In [113]:
#function takes a dataframe with OHLCV and DATETIME object as the INDEX in a %Y-%M-%D format
def window_split_data(dataframe_to_split, n_year_in_window,stock_str):
    """the function splits a monthly dataframe into 5 year windows that are non-overlapping"""
    
    #returns dataframe object with years present in the original dataframe as the index
    set_of_years = set()

    for timestamp in list(dataframe_to_split.index):
        #print (timestamp.year)
        set_of_years.add(timestamp.year)

    list_of_years_in_df = list(set_of_years)

#   #number of training test sets we will have
    len_of_list = len(list_of_years_in_df)  
    
    x = np.ceil(len_of_list/n_year_in_window)
    
    final_year_list = []
    
    for i in range(len(list_of_years_in_df)):
        if (i%x == 0.0):
            final_year_list.append(list_of_years_in_df[i])

        else:
            pass
    
#     print ("\n")

    print (final_year_list)
    
#     print ("\n")
    dataframe_to_split['Date']=dataframe_to_split.index
    
    for year in final_year_list:
        if year <=2013:
            stop = year + n_year_in_window
            start = year
            bottom = str(start)
            
            stop = str(stop)
            start = str(start)
            
            start_date = start + "-01-01"
            stop_date = stop + "-01-01"
            
            
            temp_df = dataframe_to_split.loc[(dataframe_to_split['Date'] > pd.to_datetime(start_date, format="%Y-%m-%d")) &
                                             (dataframe_to_split['Date'] < pd.to_datetime(stop_date, format="%Y-%m-%d"))]
            
            print(temp_df.head(1))
            print(temp_df.tail(1))
            print(temp_df.shape)
            print("\n")
            print("\n")
            
            temp_df = temp_df.iloc[::-1]


            
            name = "{}_{}".format(bottom,stock_str)
            temp_df.to_csv("/Users/fahad/project_repo/data/final/{}/{}.csv".format(stock_str, name))
            
        elif (year==2014) or (year ==2015):
            
            stop = 2019
            
            start = year
            bottom = str(start)
            
            start_date = str(start) + "-01-01"
            stop_date = str(stop) + "-07-01"
            
            temp_df = dataframe_to_split.loc[(dataframe_to_split['Date'] > pd.to_datetime(start_date, format="%Y-%m-%d")) &
                                             (dataframe_to_split['Date'] < pd.to_datetime(stop_date, format="%Y-%m-%d"))]
            
            print(temp_df.head(1))
            print(temp_df.tail(1))
            print(temp_df.shape)
            print("\n")
            print("\n")
            
            
            
            temp_df = temp_df.iloc[::-1]
            


            name = "{}_{}".format(bottom,stock_str)
            temp_df.to_csv("/Users/fahad/project_repo/data/final/{}/{}.csv".format(stock_str, name))


        else:
            pass

In [28]:
#set object containing the years present within a dataframe
set_of_years = set()

for timestamp in list(MSFT.index):
    #print (timestamp.year)
    set_of_years.add(timestamp.year)

list_of_years = list(set_of_years)
len_of_list = len(list_of_years)
x = np.ceil(len_of_list/5)

final_year_list = []
    
for i in range(len(list_of_years_in_df)):
    if (i%x == 0.0):
        final_year_list.append(list_of_years[i])
    else:
        pass
            
final_year_list

NameError: name 'list_of_years_in_df' is not defined

In [94]:
MSFT.index[0]

Timestamp('2019-07-26 00:00:00')